version: '3.8'
services:
  loxone-config:
    #image: "local/loxone-config:latest"
    image: "ghcr.io/lian/docker-loxone-config:main"
    container_name: loxone-config
    #build:
    #  context: .
    # dockerfile: Dockerfile
    ports:
      - "5800:5800"
    environment:
      - USER_ID=1000
      - GROUP_ID=1000
      - DISPLAY_WIDTH=1920
      - DISPLAY_HEIGHT=1080
      - HOME=/config/
      - WINEPREFIX=/config/wine
    volumes:
      - "./config:/config:rw"
